In [93]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [94]:
import os
import numpy as np
import pandas as pd

from MNM_mmnb import MNM_network_builder
import MNMAPI

In [95]:
data_folder = os.path.join('.', 'MNM_cache', 'input_files_7link_multimodal_dode_generated')

In [96]:
nb = MNM_network_builder()
nb.load_from_folder(data_folder)
nb.ID2path

OrderedDict([(0, ('driving', MNM_path, path ID 0, O node: 1, D node 6)),
             (1, ('driving', MNM_path, path ID 1, O node: 1, D node 6)),
             (2, ('driving', MNM_path, path ID 2, O node: 1, D node 6)),
             (3,
              ('bustransit',
               MNM_path_bustransit, path ID 0, O node: 1, D node 6)),
             (4,
              ('bustransit',
               MNM_path_bustransit, path ID 1, O node: 1, D node 6)),
             (5,
              ('bustransit',
               MNM_path_bustransit, path ID 2, O node: 1, D node 6)),
             (6, ('pnr', MNM_path_pnr, path ID 0, O node: 1, D node 6)),
             (7, ('pnr', MNM_path_pnr, path ID 1, O node: 1, D node 6)),
             (8, ('pnr', MNM_path_pnr, path ID 2, O node: 1, D node 6)),
             (9,
              ('bus',
               MNM_bus_route, path ID 0, route ID 1, O node: 101, D node 106)),
             (10,
              ('bus',
               MNM_bus_route, path ID 1, route ID 2, O 

In [97]:
a = MNMAPI.mmdta_api()
a.initialize(data_folder)
a

In [98]:
link_driving_array = np.array([e.ID for e in nb.link_driving_list], dtype=np.int)
a.register_links_driving(link_driving_array)

0L

In [99]:
link_bus_array = np.array([e.ID for e in nb.link_bus_list], dtype=np.int)
a.register_links_bus(link_bus_array)

0L

In [100]:
link_walking_array = np.array([e.ID for e in nb.link_walking_list], dtype=np.int)
a.register_links_walking(link_walking_array)

0L

In [101]:
path_array = np.array(list(nb.ID2path.keys()), dtype=np.int)
a.register_paths(path_array)

0L

In [102]:
a.install_cc()

0L

In [103]:
a.install_cc_tree()

0L

In [104]:
a.run_whole()

0L

In [105]:
assign_freq = nb.config.config_dict['DTA']['assign_frq']
assign_intervals = np.arange(nb.config.config_dict['FIXED']['buffer_length']//2) * assign_freq
print("assign_intervals: ")
print(assign_intervals)
end_interval = a.get_cur_loading_interval()
print("end interval: {}\n".format(end_interval))
assert(assign_intervals[-1] < end_interval)

assign_intervals: 
[  0 180 360 540 720]
end interval: 970



In [106]:
travel_stats = a.get_travel_stats()
print("\n************ travel stats ************\n")
print("car count: {}\n".format(travel_stats[0]))
print("truck count: {}\n".format(travel_stats[1]))
print("bus count: {}\n".format(travel_stats[2]))
print("passenger count: {}\n".format(travel_stats[3]))
print("car total travel time: {}\n".format(travel_stats[4]))
print("truck total travel time: {}\n".format(travel_stats[5]))
print("bus total travel time: {}\n".format(travel_stats[6]))
print("passenger total travel time: {}\n".format(travel_stats[7]))
print("\n************ travel stats ************\n")


************ travel stats ************

car count: 0.0

truck count: 53.8

bus count: 45.0

passenger count: 0.0

car total travel time: 0.0

truck total travel time: 2.53

bus total travel time: 2.40222222222

passenger total travel time: 0.0


************ travel stats ************



In [107]:
start_intervals = assign_intervals
print(start_intervals)

[  0 180 360 540 720]


In [108]:

car_link_tt = a.get_car_link_tt(start_intervals)
print(car_link_tt)

[[3.60003600e-02 3.60003600e-02 3.60003600e-02 3.60003600e-02
  3.60003600e-02]
 [5.65714286e+01 5.65714286e+01 5.65714286e+01 5.65714286e+01
  5.65714286e+01]
 [5.65714286e+01 5.65714286e+01 5.65714286e+01 5.65714286e+01
  5.65714286e+01]
 [5.65714286e+01 5.65714286e+01 5.65714286e+01 5.65714286e+01
  5.65714286e+01]
 [5.65714286e+01 5.65714286e+01 5.65714286e+01 5.65714286e+01
  5.65714286e+01]
 [5.65714286e+01 5.65714286e+01 5.65714286e+01 5.65714286e+01
  5.65714286e+01]
 [3.60003600e-02 3.60003600e-02 3.60003600e-02 3.60003600e-02
  3.60003600e-02]
 [3.60003600e-02 3.60003600e-02 3.60003600e-02 3.60003600e-02
  3.60003600e-02]
 [3.60003600e-02 3.60003600e-02 3.60003600e-02 3.60003600e-02
  3.60003600e-02]
 [3.60003600e-02 3.60003600e-02 3.60003600e-02 3.60003600e-02
  3.60003600e-02]]


In [109]:
truck_link_tt = a.get_truck_link_tt(start_intervals)
print(truck_link_tt)

[[3.600036e-02 5.000000e+00 5.000000e+00 5.000000e+00 5.000000e+00]
 [7.920000e+01 7.920000e+01 7.920000e+01 7.920000e+01 7.920000e+01]
 [7.920000e+01 1.000000e+02 7.920000e+01 9.000000e+01 7.920000e+01]
 [7.920000e+01 7.920000e+01 7.920000e+01 7.920000e+01 7.920000e+01]
 [7.920000e+01 7.920000e+01 7.920000e+01 1.050000e+02 7.920000e+01]
 [7.920000e+01 8.000000e+01 7.920000e+01 7.920000e+01 7.920000e+01]
 [3.600036e-02 5.000000e+00 5.000000e+00 5.000000e+00 5.000000e+00]
 [3.600036e-02 3.600036e-02 3.600036e-02 3.600036e-02 3.600036e-02]
 [3.600036e-02 1.000000e+01 1.000000e+01 1.000000e+01 1.000000e+01]
 [3.600036e-02 5.000000e+00 5.000000e+00 5.000000e+00 5.000000e+00]]


In [110]:
bus_link_tt = a.get_bus_link_tt(start_intervals)
print(bus_link_tt)

[[53.6399994  53.6399994  53.6399994  53.6399994  53.6399994 ]
 [65.52000269 65.52000269 65.52000269 65.52000269 65.52000269]
 [39.95999917 39.95999917 39.95999917 39.95999917 39.95999917]
 [26.28000062 26.28000062 26.28000062 26.28000062 26.28000062]
 [92.88000315 92.88000315 92.88000315 92.88000315 92.88000315]
 [65.52000269 65.52000269 65.52000269 65.52000269 65.52000269]
 [53.6399994  53.6399994  53.6399994  53.6399994  53.6399994 ]
 [39.95999917 39.95999917 39.95999917 39.95999917 39.95999917]
 [65.52000269 65.52000269 65.52000269 65.52000269 65.52000269]
 [27.36000046 27.36000046 27.36000046 27.36000046 27.36000046]
 [26.28000062 26.28000062 26.28000062 26.28000062 26.28000062]]


In [111]:
walking_link_tt = a.get_passenger_walking_link_tt(start_intervals)
print(walking_link_tt)

[[53.6399994  53.6399994  53.6399994  53.6399994  53.6399994 ]
 [65.52000269 65.52000269 65.52000269 65.52000269 65.52000269]
 [39.95999917 39.95999917 39.95999917 39.95999917 39.95999917]
 [26.28000062 26.28000062 26.28000062 26.28000062 26.28000062]
 [92.88000315 92.88000315 92.88000315 92.88000315 92.88000315]
 [65.52000269 65.52000269 65.52000269 65.52000269 65.52000269]
 [53.6399994  53.6399994  53.6399994  53.6399994  53.6399994 ]
 [39.95999917 39.95999917 39.95999917 39.95999917 39.95999917]
 [65.52000269 65.52000269 65.52000269 65.52000269 65.52000269]
 [27.36000046 27.36000046 27.36000046 27.36000046 27.36000046]
 [26.28000062 26.28000062 26.28000062 26.28000062 26.28000062]]


In [112]:
driving_path_tt = a.get_registered_path_tt_driving(start_intervals)
print(driving_path_tt)
driving_path_cost = a.get_registered_path_cost_driving(start_intervals)
print(driving_path_cost)

[[293.21485786 293.21485786 293.21485786 293.21485786 293.21485786]
 [293.21485786 293.21485786 293.21485786 293.21485786 293.21485786]
 [349.78628643 349.78628643 349.78628643 349.78628643 349.78628643]]
[[19.95362143 18.97862143 18.00362143 17.02862143 16.05362143]
 [19.95362143 18.97862143 18.00362143 17.02862143 16.05362143]
 [19.99290714 19.01790714 18.04290714 17.06790714 16.09290714]]


In [113]:
bustransit_path_tt = a.get_registered_path_tt_bustransit(start_intervals)
print(bustransit_path_tt)
bustransit_path_cost = a.get_registered_path_cost_bustransit(start_intervals)
print(bustransit_path_cost)

[[402.62000127 402.62000127 402.62000127 402.62000127 402.62000127]
 [453.48000173 453.48000173 453.48000173 453.48000173 453.48000173]
 [477.96000709 477.96000709 477.96000709 477.96000709 477.96000709]]
[[12.77959722 11.80459722 10.82959722  9.85459722  8.87959722]
 [15.56491667 14.58991667 13.61491667 12.63991667 11.66491667]
 [15.58191667 14.60691667 13.63191667 12.65691667 11.68191667]]


In [114]:
pnr_path_tt = a.get_registered_path_tt_pnr(start_intervals)
print(pnr_path_tt)
pnr_path_cost = a.get_registered_path_cost_pnr(start_intervals)
print(pnr_path_cost)

[[350.35485727 350.35485727 350.35485727 350.35485727 350.35485727]
 [286.42342991 286.42342991 286.42342991 286.42342991 286.42342991]
 [293.7834287  293.7834287  293.7834287  293.7834287  293.7834287 ]]
[[12.74330198 11.76830198 10.79330198  9.81830198  8.84330198]
 [12.69890516 11.72390516 10.74890516  9.77390516  8.79890516]
 [12.70401627 11.72901627 10.75401627  9.77901627  8.80401627]]


In [115]:
start_intervals = assign_intervals
end_intervals = assign_intervals + assign_freq
assert(end_intervals[-1] < end_interval)

In [116]:
car_link_inflow = a.get_link_car_inflow(start_intervals, end_intervals)
print(car_link_inflow)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [117]:
truck_link_inflow = a.get_link_truck_inflow(start_intervals, end_intervals)
print(truck_link_inflow)

[[10.8  9.  15.   7.  12. ]
 [15.2 14.2 18.4 12.2 17. ]
 [ 4.6  3.8  5.6  3.8  4. ]
 [10.8 10.2 13.   8.8 12. ]
 [ 7.4  8.  10.6  7.6  8.8]
 [ 3.4  4.2  5.   3.8  4.6]
 [ 9.   9.2 14.4  7.6 12. ]
 [ 0.   0.   0.   0.   0. ]
 [ 9.   9.   9.   9.   9. ]
 [ 7.4  9.2  9.   9.   9. ]]


In [118]:
bus_busstop_inflow = a.get_busstop_bus_inflow(start_intervals, end_intervals)
print(bus_busstop_inflow)

[[2.8 3.  3.  3.  3. ]
 [2.8 2.8 3.2 2.8 3.2]
 [2.6 3.  3.  3.  3. ]
 [3.  3.  3.  3.  3. ]
 [2.8 3.  3.  3.  3. ]
 [2.6 3.  3.  3.  3. ]
 [2.2 3.2 3.  3.  3. ]
 [2.8 3.2 3.  3.  3. ]
 [2.8 3.  3.  3.  3. ]
 [2.6 3.  3.  3.2 2.8]
 [2.6 3.  3.  3.  3. ]]


In [119]:
passenger_link_inflow = a.get_link_passenger_inflow(start_intervals, end_intervals)
print(passenger_link_inflow)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [120]:
def get_dar_df(dar_matrix):
    assert(dar_matrix.shape[1] == 5)
    print("path ID, departure assign interval (1 min), link ID, time interval (5 s), flow")
    dar_df = pd.DataFrame(
                    data = dar_matrix, 
                    columns = ["path_ID", "depart_assign_interval", "link_ID", "time_interval", "flow"],
                    dtype = np.float
                )
    dar_df["path_ID"] = dar_df["path_ID"].astype(np.int)
    dar_df["depart_assign_interval"] = dar_df["depart_assign_interval"].astype(np.int)
    dar_df["link_ID"] = dar_df["link_ID"].astype(np.int)
    dar_df["time_interval"] = dar_df["time_interval"].astype(np.int)
    dar_df["flow"] = dar_df["flow"].astype(np.float)
    return dar_df

In [121]:
car_dar_driving_matrix = a.get_car_dar_matrix_driving(start_intervals, end_intervals)
car_dar_driving_df = get_dar_df(car_dar_driving_matrix)
print(car_dar_driving_df)
print(car_dar_driving_df.shape)

AttributeError: 'MNMAPI.mmdta_api' object has no attribute 'get_car_dar_matrix_driving'

In [ ]:
truck_dar_driving_matrix = a.get_truck_dar_matrix_driving(start_intervals, end_intervals)
truck_dar_driving_df = get_dar_df(truck_dar_driving_matrix)
print(truck_dar_driving_df)
print(truck_dar_driving_df.shape)
print(len(nb.path_table_driving.ID2path) * len(link_driving_array) * end_interval)

In [ ]:
car_dar_pnr_matrix = a.get_car_dar_matrix_pnr(start_intervals, end_intervals)
car_dar_pnr_df = get_dar_df(car_dar_pnr_matrix)
print(car_dar_pnr_df)
print(car_dar_pnr_df.shape)

In [ ]:
bus_dar_matrix = a.get_bus_dar_matrix(start_intervals, end_intervals)
bus_dar_df = get_dar_df(bus_dar_matrix)
print(bus_dar_df)
print(bus_dar_df.shape)

In [ ]:
passenger_dar_bustransit_matrix = a.get_passenger_dar_matrix_bustransit(start_intervals, end_intervals)
passenger_dar_bustransit_df = get_dar_df(passenger_dar_bustransit_matrix)
print(passenger_dar_bustransit_df)
print(passenger_dar_bustransit_df.shape)

In [ ]:
passenger_dar_pnr_matrix = a.get_passenger_dar_matrix_pnr(start_intervals, end_intervals)
passenger_dar_pnr_df = get_dar_df(passenger_dar_pnr_matrix)
print(passenger_dar_pnr_df)
print(passenger_dar_pnr_df.shape)